// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TiendaDeRopa.Infraestructure;

namespace TiendaDeRopa.Migrations
{
    [DbContext(typeof(TiendasDbContext))]
    [Migration("20201010204235_migracionBd")]
    partial class migracionBd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TiendaDeRopa.Domain.Prenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Prendas");
                });

            modelBuilder.Entity("TiendaDeRopa.Domain.Tienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("_idPrenda")
                        .HasColumnName("PrendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("_idPrenda");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("TiendaDeRopa.Domain.Tienda", b =>
                {
                    b.HasOne("TiendaDeRopa.Domain.Prenda", "Prenda")
                        .WithMany()
                        .HasForeignKey("_idPrenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
